package services

import (
	"fmt"
	"strings"
	"sync"
)

type LocalizationService struct {
	currentLang string
	mu          sync.RWMutex
}

var (
	languages = map[string]string{
		"en": "English",
		"tr": "Türkçe",
		"de": "Deutsch",
		"fr": "Français",
		"it": "Italiano",
	}

	stringsMap = map[string]map[string]string{
		"en": {
			"app_title":              "Terminal FM Radio Player - Global & Local",
			"connecting":             "Connecting:",
			"now_playing":            "Now Playing",
			"station":                "Station",
			"country":                "Country",
			"genre":                  "Genre",
			"song":                   "Song",
			"volume":                 "Volume",
			"muted":                  "Muted",
			"recording":              "RECORDING",
			"no_stations":            "No stations found to display.",
			"total_stations":         "Total {count} stations listed.",
			"welcome_msg":            "Type 'help' for commands, 'exit' to quit.",
			"unknown_command":        "Unknown command: '{cmd}'. Type 'help' for help.",
			"error_executing":        "Error executing command: {error}",
			"shell_error":            "Shell error: {error}",
			"help_title":             "COMMAND LIST",
			"cat_listing":            "STATION LISTING",
			"cat_playback":           "PLAYBACK",
			"cat_recording":          "RECORDING",
			"cat_management":         "MANAGEMENT",
			"cat_other":              "OTHER",
			"cat_general":            "GENERAL",
			"help_general":           "help / ?            - Show this help menu",
			"exit_general":           "exit / q / quit     - Exit application",
			"stopped":                "radio stopped",
			"waiting_song":           "waiting for song info",
			"lang_select_title":      "LANGUAGE SELECTION / DİL SEÇİMİ",
			"lang_select_msg":        "Please select your language / Lütfen dilinizi seçin:",
			"lang_updated":           "Language updated to: {lang}",
			"sys_info_title":         "System Information",
			"sys_os":                 "Operating System",
			"sys_python":             "Python Version",
			"sys_cpu":                "CPU Usage",
			"sys_ram":                "System RAM",
			"sys_total_mem":          "Total Usage",
			"stats_total_time":       "Total Listening Time",
			"stats_total_sessions":   "Total Sessions",
			"stats_top_title":        "Top 10 Stations",
			"stats_no_data":          "No statistics yet.",
			"id":                     "ID",
			"name":                   "Station Name",
			"fav":                    "Fav",
			"no":                     "No",
			"cmd_listele_desc":       "Lists all radio stations",
			"cmd_turkiye_desc":       "Lists Turkish radio stations",
			"cmd_ulkeler_desc":       "Lists available countries",
			"cmd_ulke_desc":          "Lists stations of a specific country",
			"cmd_turler_desc":        "Lists available music genres",
			"cmd_tur_desc":           "Lists stations of a specific genre",
			"cmd_ara_desc":           "Search stations (name, country or genre)",
			"cmd_istatistik_desc":    "Shows listening statistics",
			"cmd_durum_desc":         "Shows current playback status",
			"cmd_sistem_desc":        "Shows system and RAM usage info",
			"cmd_temizle_desc":       "Clears the terminal screen",
			"cmd_web_desc":           "Starts the web interface in the background",
			"cmd_cal_desc":           "Plays a station by ID or index",
			"cmd_durdur_desc":        "Stops playback",
			"cmd_ses_desc":           "Changes volume level",
			"cmd_sessiz_desc":        "Mutes or unmutes playback",
			"cmd_son_desc":           "Plays the last played station",
			"cmd_sonraki_desc":       "Plays the next station in the current list",
			"cmd_onceki_desc":        "Plays the previous station in the current list",
			"cmd_karistir_desc":      "Plays a random station",
			"cmd_uyku_desc":          "Starts sleep timer",
			"cmd_gecmis_desc":        "Shows song history",
			"cmd_favori_desc":        "Adds/removes a station or current station to favorites",
			"cmd_favoriler_desc":     "Lists favorite stations",
			"cmd_kaydet_desc":        "Starts recording current stream",
			"cmd_kayitdur_desc":      "Stops recording",
			"cmd_tema_desc":          "Changes color theme",
			"cmd_kontrol_desc":       "Checks station stream URLs",
			"cmd_ekle_desc":          "Adds a new custom station",
			"cmd_duzenle_desc":       "Edits a custom station",
			"cmd_sil_desc":           "Deletes a custom station",
			"cmd_iceaktar_desc":      "Adds stations from playlist file",
			"cmd_bildirim_desc":      "Turns notifications on/off",
			"cmd_online_ara_desc":    "Search stations via RadioBrowser",
			"cmd_online_ekle_desc":   "Adds station from search results",
			"cmd_dil_desc":           "Changes application language",
			"cmd_listele_hint":       "Shows first 50 by default. Custom: listele -n NUMBER · All: listele --hepsi",
			"msg_not_playing":        "Radio is not playing!",
			"msg_already_recording":  "Already recording!",
			"msg_recording_started":  "Recording started: {file}",
			"msg_recording_failed":   "Could not start recording: {error}",
			"msg_no_active_record":   "No active recording.",
			"msg_recording_stopped":  "Recording stopped. Saved to: {path}",
			"msg_recording_stopped_simple": "Recording stopped.",
			"msg_playing":            "Playing: {name}",
			"msg_stop_playing":       "Playback stopped.",
			"msg_vol_set":            "Volume set to: {vol}%",
			"msg_muted":              "Playback muted.",
			"msg_unmuted":            "Playback unmuted.",
			"msg_no_last_station":    "No last played station record.",
			"msg_last_station_missing": "Last played station no longer exists.",
			"msg_need_list":          "Please create a list first (e.g., listele, turkiye).",
			"msg_no_playing_station": "No station currently playing.",
			"msg_station_not_in_list": "Current station not found in the last list.",
			"msg_no_match":           "No station found matching the criteria.",
			"msg_sleep_cancel":       "Sleep timer cancelled.",
			"msg_no_sleep":           "No active sleep timer.",
			"msg_sleep_set":          "Sleep timer set: will stop in {min} minutes.",
			"msg_sleep_done":         "Sleep timer finished, playback stopped.",
			"msg_no_history":         "No song history yet.",
			"msg_recent_songs":       "Recent songs:",
			"msg_fav_added":          "Added to favorites: {name}",
			"msg_fav_removed":        "Removed from favorites: {name}",
			"msg_station_not_found":  "Station not found.",
			"msg_custom_only":        "Only custom stations can be edited.",
			"msg_station_updated":    "Station updated.",
			"msg_station_deleted":    "Station deleted: {id}",
			"msg_station_added":      "Custom station added: {name}",
			"msg_import_success":     "{count} stations imported.",
			"msg_import_fail":        "Could not read stations or file not found.",
			"msg_notify_on":          "Desktop notifications on.",
			"msg_notify_off":         "Desktop notifications off.",
			"msg_searching":          "Searching...",
			"msg_search_results":     "Online Search Results",
			"msg_online_add_hint":    "To add: online-ekle -n <no>",
			"msg_checking":           "{count} stations being checked... (This may take a while)",
			"msg_check_done":         "Check complete: {success}/{total} active.",
			"msg_active":             "ACTIVE",
			"msg_failed":             "FAILED",
			"msg_error":              "ERROR",
			"web_now_playing":        "NOW PLAYING",
			"web_loading":            "Loading...",
			"web_stop":               "Stop",
			"web_mute":               "Mute",
			"web_unmute":             "Unmute",
			"web_previous":           "Previous",
			"web_next":               "Next",
			"web_shuffle":            "Shuffle",
			"web_favorite":           "Favorite",
			"web_unfavorite":         "Unfavorite",
			"web_search_placeholder": "Search a radio station or genre...",
			"web_stations_loading":   "Loading stations...",
			"web_no_results":         "No results found.",
			"web_system_status":      "System Status",
			"web_close":              "Close",
			"web_live":               "Live Broadcast",
			"web_connecting":         "Connecting...",
			"web_subtitle":           "Terminal FM Radio Player - Web Edition",
			"web_theme_shell":        "Shell Glass",
			"web_theme_premium":      "Premium Radio",
			"web_theme_compact":      "Compact Dashboard",
			"web_theme_neon":         "Neon Live",
			"web_theme_midnight":     "Midnight",
			"web_theme_sakura":       "Sakura",
			"web_theme_retro":        "Retro CRT",
			"web_theme_brutalist":    "Brutalist",
			"web_theme_car":          "Vintage Car Radio",
			"web_theme_win95":        "Windows 95",
			"web_theme_winamp_classic": "Winamp Classic",
			"web_theme_besiktas_bjk": "Beşiktaş BJK",
			"web_filter_all":         "All",
			"web_filter_favorites":   "Favorites",
			"web_recording":          "Recording",
			"web_record":             "Record",
			"web_play":               "Play",
			"web_playing_short":      "Playing",
			"web_unknown_genre":      "Unknown genre",
			"web_unknown_country":    "Unknown country",
			"web_toggle_favorite":    "Toggle favorite",
			"web_favorite_added":     "Added to favorites",
			"web_favorite_removed":   "Removed from favorites",
			"web_recording_updated":  "Recording updated.",
		},
		"tr": {
			"app_title":              "Terminal FM Radyo Çalar - Türkiye & Dünya",
			"connecting":             "Bağlanıyor:",
			"now_playing":            "Çalıyor",
			"station":                "Radyo",
			"country":                "Ülke",
			"genre":                  "Tür",
			"song":                   "Şarkı",
			"volume":                 "Ses",
			"muted":                  "Sessiz",
			"recording":              "KAYIT YAPILIYOR",
			"no_stations":            "Gösterilecek istasyon bulunamadı.",
			"total_stations":         "Toplam {count} istasyon listelendi.",
			"welcome_msg":            "Komutlar için 'help', çıkmak için 'exit' yazın.",
			"unknown_command":        "Bilinmeyen komut: '{cmd}'. Yardım için 'help' yazın.",
			"error_executing":        "Komut çalıştırılırken hata: {error}",
			"shell_error":            "Shell hatası: {error}",
			"help_title":             "KOMUT LİSTESİ",
			"cat_listing":            "İSTASYON LİSTELEME",
			"cat_playback":           "OYNATMA",
			"cat_recording":          "KAYIT",
			"cat_management":         "YÖNETİM",
			"cat_other":              "DİĞER",
			"cat_general":            "GENEL",
			"help_general":           "help / ?            - Bu yardım menüsünü gösterir",
			"exit_general":           "exit / q / quit     - Uygulamadan çıkar",
			"stopped":                "radyo durduruldu",
			"waiting_song":           "şarkı bilgisi bekleniyor",
			"lang_select_title":      "DİL SEÇİMİ",
			"lang_select_msg":        "Lütfen dilinizi seçin:",
			"lang_updated":           "Dil güncellendi: {lang}",
			"sys_info_title":         "Sistem Bilgileri",
			"sys_os":                 "İşletim Sistemi",
			"sys_python":             "Python Sürümü",
			"sys_cpu":                "CPU Kullanımı",
			"sys_ram":                "Sistem RAM",
			"sys_total_mem":          "Toplam Kullanım",
			"stats_total_time":       "Toplam Dinleme",
			"stats_total_sessions":   "Toplam Oturum",
			"stats_top_title":        "Top 10 İstasyon",
			"stats_no_data":          "Henüz istatistik yok.",
			"id":                     "ID",
			"name":                   "İstasyon İsmi",
			"fav":                    "Fav",
			"no":                     "No",
			"cmd_listele_desc":       "Tüm radyo istasyonlarını listeler",
			"cmd_turkiye_desc":       "Türkiye radyo istasyonlarını listeler",
			"cmd_ulkeler_desc":       "Mevcut ülkeleri listeler",
			"cmd_ulke_desc":          "Belirli bir ülkenin istasyonlarını listeler",
			"cmd_turler_desc":        "Mevcut müzik türlerini listeler",
			"cmd_tur_desc":           "Belirli bir müzik türündeki istasyonları listeler",
			"cmd_ara_desc":           "İstasyon arar (isim, ülke veya tür)",
			"cmd_istatistik_desc":    "Dinleme istatistiklerini gösterir",
			"cmd_durum_desc":         "Şu anki çalma durumunu gösterir",
			"cmd_sistem_desc":        "Sistem ve RAM kullanım bilgilerini gösterir",
			"cmd_temizle_desc":       "Terminal ekranını temizler",
			"cmd_web_desc":           "Web arayüzünü arka planda başlatır",
			"cmd_cal_desc":           "ID veya No ile istasyon oynatır",
			"cmd_durdur_desc":        "Oynatmayı durdurur",
			"cmd_ses_desc":           "Ses seviyesini değiştirir",
			"cmd_sessiz_desc":        "Oynatmayı sessize alır veya sesi açar",
			"cmd_son_desc":           "En son çalınan istasyonu oynatır",
			"cmd_sonraki_desc":       "Listedeki bir sonraki istasyona geçer",
			"cmd_onceki_desc":        "Listedeki bir önceki istasyona geçer",
			"cmd_karistir_desc":      "Rastgele bir istasyon çalar",
			"cmd_uyku_desc":          "Uyku zamanlayıcısını başlatır",
			"cmd_gecmis_desc":        "Şarkı geçmişini gösterir",
			"cmd_favori_desc":        "İstasyonu veya çalan istasyonu favorilere ekler/çıkarır",
			"cmd_favoriler_desc":     "Favori istasyonları listeler",
			"cmd_kaydet_desc":        "Çalan yayını kaydetmeye başlar",
			"cmd_kayitdur_desc":      "Kaydı durdurur",
			"cmd_tema_desc":          "Renk temasını değiştirir",
			"cmd_kontrol_desc":       "İstasyon akış URL'lerini kontrol eder",
			"cmd_ekle_desc":          "Yeni özel istasyon ekler",
			"cmd_duzenle_desc":       "Özel istasyonu düzenler",
			"cmd_sil_desc":           "Özel istasyonu siler",
			"cmd_iceaktar_desc":      "Playlist dosyasından istasyon ekler",
			"cmd_bildirim_desc":      "Bildirimleri açar/kapatır",
			"cmd_online_ara_desc":    "RadioBrowser üzerinden istasyon arar",
			"cmd_online_ekle_desc":   "Arama sonucundan istasyon ekler",
			"cmd_dil_desc":           "Uygulama dilini değiştirir",
			"cmd_listele_hint":       "Varsayılan ilk 50 gösterir. Özel adet: listele -n SAYI · Tümü: listele --hepsi",
			"msg_not_playing":        "Radyo çalmıyor!",
			"msg_already_recording":  "Zaten kayıt yapılıyor!",
			"msg_recording_started":  "Kayıt başladı: {file}",
			"msg_recording_failed":   "Kayıt başlatılamadı: {error}",
			"msg_no_active_record":   "Aktif kayıt yok.",
			"msg_recording_stopped":  "Kayıt durduruldu. Şuraya kaydedildi: {path}",
			"msg_recording_stopped_simple": "Kayıt durduruldu.",
			"msg_playing":            "Çalınıyor: {name}",
			"msg_stop_playing":       "Oynatma durduruldu.",
			"msg_vol_set":            "Ses seviyesi ayarlandı: %{vol}",
			"msg_muted":              "Oynatma sessize alındı.",
			"msg_unmuted":            "Oynatma sesi açıldı.",
			"msg_no_last_station":    "Son çalınan istasyon kaydı yok.",
			"msg_last_station_missing": "Son çalınan istasyon artık bulunmuyor.",
			"msg_need_list":          "Önce bir liste oluşturun (örn: listele, turkiye).",
			"msg_no_playing_station": "Şu an çalan bir istasyon yok.",
			"msg_station_not_in_list": "Mevcut istasyon son listede bulunamadı.",
			"msg_no_match":           "Kriterlere uygun istasyon bulunamadı.",
			"msg_sleep_cancel":       "Uyku zamanlayıcısı iptal edildi.",
			"msg_no_sleep":           "Aktif uyku zamanlayıcısı yok.",
			"msg_sleep_set":          "Uyku zamanlayıcısı ayarlandı: {min} dakika sonra duracak.",
			"msg_sleep_done":         "Uyku zamanlayıcısı süresi doldu, oynatma durduruldu.",
			"msg_no_history":         "Henüz şarkı geçmişi yok.",
			"msg_recent_songs":       "Son çalınan şarkılar:",
			"msg_fav_added":          "Favorilere eklendi: {name}",
			"msg_fav_removed":        "Favorilerden çıkarıldı: {name}",
			"msg_station_not_found":  "İstasyon bulunamadı.",
			"msg_custom_only":        "Yalnızca özel istasyonlar düzenlenebilir.",
			"msg_station_updated":    "İstasyon güncellendi.",
			"msg_station_deleted":    "İstasyon silindi: {id}",
			"msg_station_added":      "Özel istasyon eklendi: {name}",
			"msg_import_success":     "{count} istasyon içe aktarıldı.",
			"msg_import_fail":        "İstasyon okunamadı veya dosya bulunamadı.",
			"msg_notify_on":          "Masaüstü bildirimleri açıldı.",
			"msg_notify_off":         "Masaüstü bildirimleri kapatıldı.",
			"msg_searching":          "Aranıyor...",
			"msg_search_results":     "Online Arama Sonuçları",
			"msg_online_add_hint":    "Eklemek için: online-ekle -n <no>",
			"msg_checking":           "{count} istasyon kontrol ediliyor... (Zaman alabilir)",
			"msg_check_done":         "Kontrol tamamlandı: {success}/{total} aktif.",
			"msg_active":             "AKTİF",
			"msg_failed":             "BAŞARISIZ",
			"msg_error":              "HATA",
			"web_now_playing":        "ŞU AN ÇALIYOR",
			"web_loading":            "Yükleniyor...",
			"web_stop":               "Durdur",
			"web_mute":               "Sessize Al",
			"web_unmute":             "Sesi Aç",
			"web_previous":           "Önceki",
			"web_next":               "Sonraki",
			"web_shuffle":            "Karıştır",
			"web_favorite":           "Favori",
			"web_unfavorite":         "Favoriden Çıkar",
			"web_search_placeholder": "Bir radyo istasyonu veya tür ara...",
			"web_stations_loading":   "İstasyonlar yükleniyor...",
			"web_no_results":         "Sonuç bulunamadı.",
			"web_system_status":      "Sistem Durumu",
			"web_close":              "Kapat",
			"web_live":               "Canlı Yayın",
			"web_connecting":         "Bağlanıyor...",
			"web_subtitle":           "Terminal FM Radyo Çalar - Web Sürümü",
			"web_theme_shell":        "Shell Glass",
			"web_theme_premium":      "Premium Radyo",
			"web_theme_compact":      "Kompakt Panel",
			"web_theme_neon":         "Neon Canlı",
			"web_theme_midnight":     "Gece Yarısı",
			"web_theme_sakura":       "Sakura",
			"web_theme_retro":        "Retro CRT",
			"web_theme_brutalist":    "Brutalist",
			"web_theme_car":          "Vintage Car Radio",
			"web_theme_win95":        "Windows 95",
			"web_theme_winamp_classic": "Winamp Classic",
			"web_theme_besiktas_bjk": "Beşiktaş BJK",
			"web_filter_all":         "Tümü",
			"web_filter_favorites":   "Favoriler",
			"web_recording":          "Kayıt",
			"web_record":             "Kaydet",
			"web_play":               "Oynat",
			"web_playing_short":      "Çalıyor",
			"web_unknown_genre":      "Bilinmeyen tür",
			"web_unknown_country":    "Bilinmeyen ülke",
			"web_toggle_favorite":    "Favori durumunu değiştir",
			"web_favorite_added":     "Favorilere eklendi",
			"web_favorite_removed":   "Favorilerden çıkarıldı",
			"web_recording_updated":  "Kayıt güncellendi.",
		},
	}

	L = &LocalizationService{currentLang: "tr"}
)

func (ls *LocalizationService) SetLanguage(lang string) {
	ls.mu.Lock()
	defer ls.mu.Unlock()
	if _, ok := languages[lang]; ok {
		ls.currentLang = lang
	}
}

func (ls *LocalizationService) GetLanguage() string {
	ls.mu.RLock()
	defer ls.mu.RUnlock()
	return ls.currentLang
}

func (ls *LocalizationService) GetLanguages() map[string]string {
	return languages
}

func (ls *LocalizationService) Get(key string, args ...interface{}) string {
	ls.mu.RLock()
	defer ls.mu.RUnlock()

	langStrings, ok := stringsMap[ls.currentLang]
	if !ok {
		langStrings = stringsMap["en"]
	}

	text, ok := langStrings[key]
	if !ok {
		text = stringsMap["en"][key]
		if text == "" {
			return key
		}
	}

	if len(args) > 0 {
		// Simple named parameter replacement for keys like {count}, {lang}
		// Since Go doesn't have a direct equivalent to Python's .format(**kwargs),
		// we'll handle common cases manually or expect a specific order.
		// For now, let's implement a simple replacement for {key} with %v style if needed,
		// but the current Python code uses named placeholders.

		// To match Python's behavior, we'd need to pass a map or use a more complex replacement.
		// Let's implement a simple map-based replacement if the first arg is a map.
		if m, ok := args[0].(map[string]interface{}); ok {
			for k, v := range m {
				placeholder := fmt.Sprintf("{%s}", k)
				text = strings.ReplaceAll(text, placeholder, fmt.Sprintf("%v", v))
			}
		}
	}

	return text
}
